version: '3.8'

services:
  auth-service:
    build: ./auth-service
    container_name: auth-container
    ports:
      - "8000:80"

  symptom-service:
    build: ./symptom-service
    container_name: symptom-container
    ports:
      - "8001:80"

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3000:80"
