name: Deploy Auth Service

on:
  push:
    paths:
      - 'auth-service/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag and Push
      run: |
        docker build -t auth-service ./auth-service
        docker tag auth-service:latest ${{ secrets.ECR_REPO_AUTH }}:latest
        docker push ${{ secrets.ECR_REPO_AUTH }}:latest
