name: Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag and Push
      run: |
        docker build -t frontend ./frontend
        docker tag frontend:latest ${{ secrets.ECR_REPO_FRONTEND }}:latest
        docker push ${{ secrets.ECR_REPO_FRONTEND }}:latest
