name: Deploy Symptom Service

on:
  push:
    paths:
      - 'symptom-service/**'
      - '.github/workflows/symptom-service.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t symptom-service ./symptom-service

      - name: Tag and Push image to ECR
        run: |
          docker tag symptom-service:latest ${{ secrets.ECR_REPO_SYMPTOM
